  version: '3'

  services:
    web:
      container_name: 'thcorner-container'
      image: ketan2004/thcorner:latest
      depends_on:
        - db
      ports:
        - '4000:80'
      volumes:
        - data_volume_new:/var/www/html/
      

    db:
      container_name: mysql_container
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 'Ketan123' 
      ports:
        - '5000:3306'
      volumes:
        - db_data_new:/var/lib/mysql

    
    php_my_admin:
      container_name: php_my_admin
      image: phpmyadmin
      restart: always
      ports:
        - '5001:80'
      environment:
        - PMA_PORT=5000
        - MYSQL_ROOT_PASSWORD=Ketan123
      
  volumes:
    data_volume_new:
      driver: local
    db_data_new:
      driver: local